version: '3'
services:
    database:
        container_name: database-entla
        image: postgis/postgis:13-master
        # Required when running on platform other than amd64, like Apple M1/M2:
        # platform: linux/amd64
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'
        ports:
            - 5432:5432

    cache:
        container_name: cache-entla
        image: redis:6

    directus:
        container_name: directus-entla
        image: directus/directus:10.10
        ports:
            - 8054:8055
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            KEY: '255d861b-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6116487b-b5b5-52c2-cda1-c8022c45e263'

            # Activate websockets
            WEBSOCKETS_ENABLED: true

            # Get vrom environment variable
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}

            # Other Settinsg
            EMAIL_FROM: ${EMAIL_FROM}

            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: true
            # Clear Cache if data is altered or added
            CACHE_AUTO_PURGE: true
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'

            ADMIN_EMAIL: 'kontakt@abteilung.ch'
            ADMIN_PASSWORD: '5>-5tPX~dZc5'

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            PUBLIC_URL: 'https://studio.flohmarktkanzlei.ch'
            CORS_ENABLED: true

        # Environment variables can also be defined in a file (for example `.env`):
        # env_file:
        #     - .env
