version: '3'
services:
    nginx:
        container_name: entla24mysql-nginx
        image: nginx:1.21
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - '91:80'
        restart: always
        depends_on:
            - directus

    database:
        container_name: entla24mysql-database
        image: mysql:5.7
        platform: linux/amd64
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 5103:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'directus'
            MYSQL_DATABASE: 'directus'
            MYSQL_USER: 'directus'
            MYSQL_PASSWORD: 'directus'

    cache:
        container_name: entla24mysql-cache
        image: redis:7

    directus:
        container_name: entla24mysql-directus
        image: directus/directus:10.11.2
        ports:
            - 8058:8055
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            KEY: '5d861b25-5699-a15e-93aa-c40b1922530e'
            SECRET: '6187b164-b55b-c252-a1cd-c85e263022c4'

            # Activate websockets
            WEBSOCKETS_ENABLED: 'true'

            # Get from environment variable
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}

            # Other Settings
            EMAIL_FROM: ${EMAIL_FROM}

            DB_CLIENT: 'mysql'
            DB_HOST: 'database'
            DB_PORT: '3306'
            DB_DATABASE: 'directus'
            DB_USER: 'root'
            DB_PASSWORD: 'directus'
            DB_CHARSET: 'utf8mb4' # Setzen Sie den Zeichensatz für die Datenbankverbindung

            MYSQL_USER: 'directus'
            MYSQL_PASSWORD: 'directus'
            MYSQL_DATABASE: 'directus'

            MYSQL_ROOT_PASSWORD: 'directus'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'

            CACHE_ENABLED: true
            # Clear Cache if data is altered or added
            CACHE_AUTO_PURGE: true
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'

            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            PUBLIC_URL: 'https://studio.entla.ch'
            CORS_ENABLED: true

        # Environment variables can also be defined in a file (for example `.env`):
        # env_file:
        #   - .env
